### ISSUE TITLE
Please do not post the solution before 100 people solved the problem.

### ISSUE THREAD

**Issue by user202729** [luckytoilet/projecteuler-solutions#8]
This is the graph of fastest solvers of the currently-only problem that has less than 100 solvers. ([Problem 696](https://projecteuler.net/problem=696))

![a](https://user-images.githubusercontent.com/25191436/93906580-8cbcf600-fd26-11ea-8edf-3906c352d0cc.png)

The horizontal line is the time the solution is committed. (https://github.com/luckytoilet/projecteuler-solutions/commit/cf08a037b09242539385b624566b27839583cd19) The vertical axis is the time (in seconds) since the problem is posted, the horizontal axis is the number of people solved the problem.

I am not that good at statistics to see what's the probability of that happening by chance, but it is pretty clear just by looking at it.

![b](https://user-images.githubusercontent.com/25191436/93906592-8fb7e680-fd26-11ea-9685-f043f47f1bf0.png)

If you insists on posting the answers despite PE's rules, at least **don't** post them before the fastest solvers table is finished.

**Comment by luckytoilet** [comment]
Interesting graph. It looks like the effect is small, even after 2 months of the solution being public, there's still less than 100 solvers. It may be due to summer, since no new problems are released and university students having more spare time. Correlation is not causation, and it's hard to draw any conclusions from it.

As for withholding answers before 100 solvers, this has been discussed many times already. My policy is publishing answers as soon as I have it.

**Comment by b0w1d** [comment]
I can't see any good reason to publish all the answers (and just the answers) like this. You try to defend yourself by saying that it's people's own decision whether they want to cheat, but seriously, what else does this achieve? It is written clearly in their site that the purpose of PE isn't for people to learn from others' solution and you should respect that as a (presumably freemium) user. 

And it least ruined my motivation as a user who once wanted to solve as many problems as possible, because now it is not as impressive to have many problems solved as before given that the answers are so readily accessible.

I know that you still don't care, but I'm just ranting here and feeling sad that PE isn't commercial like some CTF sites that actually have staffs tracking down leaked solutions. For now on PE my only worthwhile joy is to solve the most recent problem before it gets published here.

**Comment by luckytoilet** [comment]
Sorry that I have ruined your appreciation of PE, but projecteuler-solutions has existed since 2009 and is here to stay. You can still solve the problems for your own satisfaction, or compete in the leaderboard by solving them the fastest.
