### ISSUE TITLE
I got a different answer for problem 165

### ISSUE THREAD

**Issue by nagydani** [luckytoilet/projecteuler-solutions#9]
My answer is 2868997, which is in the same ballpark as yours, but it's a different number.
Now, I don't know how you arrived at your solution, but I wrote a fairly straightforward Haskell program that generates all segments, then pairs them up and then checks each pair if they form a true intersection. It is quite slow, but I don't see how it can be incorrect.
If requested, I can show my code, it is quite short and self-explanatory.
Note that Project Nayuki does not have a solution for this problem.

**Comment by luckytoilet** [comment]
I have not personally looked at that problem. You might have more luck asking on [this forum](https://www.tapatalk.com/groups/eulersolutionsfr/), or use the answer to unlock the official forum if you're stuck.

**Comment by nagydani** [comment]
> I have not personally looked at that problem.
Okay, I found the error in my reasoning, fixed my code and got the right answer. Missed the word "distinct" in the problem statement.

**Comment by nayuki** [comment]
I took a look at [problem #165](https://projecteuler.net/problem=165) because you mentioned it here. It was easy to understand so I decided to take a stab at solving it. Solving the system of linear equations for the geometric intersection was annoying, as was carefully minding the edge/corner cases. Although I made a lot of mistakes along the way, I finished my solution in a long afternoon. Btw, my Java solution runs in 10 seconds, whereas my Python solution runs in 230 seconds. Memory usage is high though.
